### ISSUE TITLE
[Data Pipelines] API HTML Renderer

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#267]
## spec
if there is a snippet defined under Snippets with 
<img width="1728" alt="Screen Shot 2022-04-16 at 4 17 52 PM" src="https://user-images.githubusercontent.com/35935196/163690165-ffcb8b40-39f7-4ba9-9c9b-0839d3a68650.png">

the same `identifier` as an API Namespace `slug`

<img width="1728" alt="Screen Shot 2022-04-16 at 4 16 54 PM" src="https://user-images.githubusercontent.com/35935196/163690170-41728a91-36de-4256-84ac-dc976250bc3d.png">

then the snippet should be able to:

1. reference the exposed `api_resource` 
2. parse Ruby interpolated strings the [same way as API Actions](https://github.com/restarone/violet_rails/wiki/API:-Entities,-Form-Rendering,-Interfaces-and-Actions#example-discord-bot)

an API Namespace should be able to be rendered by calling a helper function to render lists of API Resources (with activerecord query interface support). For example: the following will render all the API Resources submitted by the current user:

``` ruby
{{ cms:helper render_api_namespace_resource_index, "api_namespace_slug_here", scope: { current_user: true }, order: { created_at: 'desc' } }}  
```

In the above API Namespace, convention would follow that there is a `user_id` in every API Resource that is used for scoping. Scope should also support scoping by API Resource properties. Eg: where enum values are used

`scope: { properties: { synced_to_mailchimp: false } }`

How Comfy handles something like this: 
https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Render-Non-Comfy-Models-as-Pages

**Comment by donrestarone** [comment]
This feature will support the following project: 
<img width="1728" alt="Screen Shot 2022-07-24 at 3 41 40 PM" src="https://user-images.githubusercontent.com/35935196/180663356-1927a130-b775-4a9e-9f93-949ef5c09a8a.png">
<img width="1728" alt="Screen Shot 2022-07-24 at 3 41 32 PM" src="https://user-images.githubusercontent.com/35935196/180663358-0aae8550-36a7-46b1-9f67-d4589a51ee73.png">

**Comment by Pralish** [comment]
## HOW TO USE

#### Api Resource Index

- create snippet with identifier same as api_namespace slug
- Variables available on snippet: @api_resources & @api_namespace
- Render the snippet on any page with this helper: {{cms:helper render_api_namespace_resource_index 'identifier'}}
- Is filterable using query params, eg: http://lvh.me:5250/?properties={"synced":"false"}

#### Api Resource show

- create snippet with  identifier as api_namespace slug with '-show' at the end, eg: people-show
- Variables available on snippet: @api_resource & @api_namespace
- Render the snippet on any page with this helper: {{cms:helper render_api_namespace_resource 'identifier'}}
- id query params is mandetory, will raise 404 otherwise. eg: http://lvh.me:5250/?id=123
